# Generated by Django 5.0.6 on 2024-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirs_sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparameters',
            name='imm_boost',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='simulationparameters',
            name='prob',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='simulationparameters',
            name='timestep',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='simulationparameters',
            name='use_vaccine',
            field=models.BooleanField(default=False),
        ),
    ]
