# Generated by Django 5.0.6 on 2024-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirs_sim', '0003_rename_prob_simulationparameters_rel_beta_inf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparameters',
            name='n_agents',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='simulationparameters',
            name='n_timesteps',
            field=models.IntegerField(default=20),
        ),
    ]
