# Generated by Django 5.0.6 on 2024-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirs_sim', '0006_remove_simulationparameters_probabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparameters',
            name='probs',
            field=models.CharField(default='0.3, 0.5', max_length=100),
        ),
    ]
