# Generated by Django 5.0.6 on 2024-07-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirs_sim', '0007_simulationparameters_probs'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparameters',
            name='age_range',
            field=models.CharField(default='0.75, 1.5', max_length=100),
        ),
    ]
