# Generated by Django 5.0.6 on 2024-07-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seirs_sim', '0008_simulationparameters_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationparameters',
            name='mean_dur_infection',
            field=models.FloatField(default=5.0),
        ),
    ]
